openapi: 3.0.0
info:
  description: <-
    The intent of this API is to provide a consistent/standardized mechanism to create new
    documents, delete existing documents, retrieving information about uploaded documents. This Specification
    is based on TMF667 - Document Management Release 17.0.1 from November 2017.
  version: 0.0.1
  title: Doc Box API
  license:
    name: MIT
servers:
  - url: 'https://{restapi_id}.execute-api.{region}.amazonaws.com/{stage_name}/documentManagement'
paths:
  /document:
    post:
      summary: 'This operation creates a Document entity.'
      operationId: 'createDocument'
      requestBody:
        description: ''
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/Document_Create'
      responses:
        201:
          description: 'Created'
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/Document_Create_Resp'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: 'Internal Server Error'
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Document_Create:
      description: 'This is the document resource when creating new documents'
      type: object
      allOf:
        - $ref: '#/components/schemas/Document'

    Document_Create_Resp:
      description: 'This is a document resource allowing meta-data and the information of the document model.'
      type: object
      required:
        - id
        - lifecycleState
      allOf:
        - $ref: '#/components/schemas/Document'
      properties:
        _links:
          $ref: '#/components/schemas/Links'
        id:
          description: 'Identifier of the document.'
          type: string
        lifecycleState:
          description: 'The lifecycleState of the document, such as Active.'
          type: string
        creationDate:
          description: 'The date and time the document was created.'
          type: string
          format: date-time

    Document:
      description: 'This is a document resource allowing meta-data and the information of the document model.'
      type: object
      properties:
        type:
          description: 'Name of the document type'
          type: string
        name:
          description: 'A string used to give a name to the document'
          type: string

    Error:
      description: 'Used when an API throws an Error, typically with a HTTP error response-code (4xx, 5xx).'
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: 'Application specific error code, defined in the API or a common list.'
        message:
          type: string
          description: 'More details and corrective actions related to the error which can be shown to a client user.'

    Links:
      description: 'Link reference to the resource itself.'
      type: object
      properties:
        self:
          $ref: '#/components/schemas/HALSelfLink'
    HALSelfLink:
      description: 'Hyperlink reference to the resource itself.'
      required:
        - href
      type: object
      properties:
        href:
          description: 'URI reference to the resource itself.'
          type: string